### ISSUE TITLE
Move detectability calculation to digestion to avoid overhead

### ISSUE THREAD

**Issue by veitveit** [veitveit/PhosFake#1]

**Comment by veitveit** [comment]
AND change to quantile filtering for the RFScore

**Comment by veitveit** [comment]
Quantile filtering is done, and I am not sure whether to move the other one to digestion yet.

**Comment by mlocardpaulet** [comment]
Just a thought:
right now, if I understand well, we "just" remove the less detectable peptides. So in our pipeline, the quantification is never impacted by flyability, right? 
I wonder if instead we should not apply a "flyability factor" to the peptide quantities. And then filter based on the resulting relative quantities...

**Comment by veitveit** [comment]
I understand that detectability is the combined flyability and LC "performance". 
Is there any study that is able to predict actual flyability? The last time I heard that term, they corrected it to detectability when I asked :-).

**Comment by mlocardpaulet** [comment]
I think that you are right, sorry. But then replace "flyability" by "detectability" in my message. The question remains...

**Comment by veitveit** [comment]
Ups, I did not realize that :-)

**Comment by veitveit** [comment]
Now I think I got your point :-). 

So you mean the detectability could be used to filter on basis of the quantitative values? The question then would be how. There seem to be many possibilities.

**Comment by mlocardpaulet** [comment]
we could multiply each quantity with the detectability factor determined by the model. 
It would reduce the signal of the less-detectable peptides. 
Then, when using the detection threshold, we would remove the less abundant peptidoforms, this would result from the combination of their initial signal and their detectability.

**Comment by veitveit** [comment]
Not sure how much impact this would have on the distributions as they then will be influenced by the distribution of detectability scores. Or am I wrong here?

**Comment by mlocardpaulet** [comment]
yeah... Also, the detectability factor as calculated with peptideranger has nothing to do with signal (although it may be a confounding factor). The metric used for training is the proportion a runs a given peptide is identified divided by the total number of runs.

**Comment by veitveit** [comment]
Done
