### ISSUE TITLE
two names for the digestion output: "outputDigest_" and "outputDigestion_"

### ISSUE THREAD

**Issue by mlocardpaulet** [veitveit/PhosFake#11]
When I run `run_sims(Param, phosfake_config)`, among the files generated some are named "outputDigest_" and some "outputDigestion_". I have a bit of both. I think that it may depend on the presence of missed cleavages (PropMissedCleavages == 0 or PropMissedCleavages > 0), but I am not sure.

**Comment by veitveit** [comment]
@mlocardpaulet I changed the "Digestion" to "Digest" for consistency with parameter names. The "outputDigestion" files will not be read anymore
