### ISSUE TITLE
notes regarding installation (not a real issue)

### ISSUE THREAD

**Issue by mlocardpaulet** [veitveit/PhosFake#3]
I followed the steps described in the vignette to install PhosFake. 

It worked nicely on my side. The only slight issues I had were:
```
ERROR: dependency ‘PeptideRanger’ is not available for package ‘PhosFake’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/PhosFake’
Warning messages:
1: package ‘cleaver’ is not available for this version of R
```

So I had to install the packages 'cleaver' (https://www.bioconductor.org/packages/release/bioc/html/cleaver.html) and 'PeptideRanger' (https://github.com/rr-2/PeptideRanger) alone. We could consider adding a bit of information about this in the Vignette. 

Once these were installed, I reran the PhosFake install and it worked like a charm.

**Comment by veitveit** [comment]
This should be solvable, most likely just by adding the cleaver package to the dependencies. Did that now but need to confirm that it is working.

**Comment by veitveit** [comment]
Should work automatically now as I added all dependencies
