### ISSUE TITLE
Request: get previous parameters

### ISSUE THREAD

**Issue by mlocardpaulet** [veitveit/PhosFake#8]
Right now, we need to provide parameters to get the corresponding PhosFake results, all the results that are saved but do not match exactly the parameters are ignored.
It could be useful to have a function that retrieves all the parameters corresponding to the files in a given folder (only previous phosFake outputs of course). This way, one can check what was previously generated without having to remember the exact parameters that were used. 
Does this make sense?

**Comment by veitveit** [comment]
It makes sense!
